apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-cloud-serverless
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-cloud-serverless
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: 17
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
